services:
  flask:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PIP_REQUIREMENTS: requirements/base.txt
        #NODE_VERSION: 20
    image: galacat/flask-${WEB_ENV}
    container_name: galacat-flask-${WEB_ENV}-container

    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app
      - WEB_ENV=${WEB_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/code
      - ../galacat-volumes/bucket:/bucket
      #- ../galacat-volumes/logs/flask:/var/log/galacat
    command: /srv/start

  postgres:
    #build:
    #  context: .
    #  dockerfile: ./docker/Dockerfile_postgres
    #  args:
    #    POSTGRES_VERSION: 16
    #    DEBIAN_RELEASE: bookworm
    image: postgres:17-bookworm
    container_name: galacat-postgres-${WEB_ENV}-container
    restart: no
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../galacat-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
      - ../galacat-volumes/bucket:/bucket
    #command: ["postgres", "-c", "log_statement=all"]
#  redis:
    #image: redis:7-alpine
    #
    #restart: no
